[theme]
primaryColor = "#FF69B4" # Brighter pink for interactive elements
backgroundColor = "#FFD1DC" # Soft pink for main content area
secondaryBackgroundColor = "#FFB6C1" # Light pink for sidebar and widgets
textColor = "#000000" # Black text for contrast
